###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka
    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true

hystrix:
  metrics:
    polling-interval-ms: 5000
    enabled: true
spring:
  ###Druid连接池配置
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.50:3306/krt-cloud?characterEncoding=utf8&useSSL=true&allowMultiQueries=true
      username: root
      password: 1234
      initial-size: 1
      min-idle: 1
      max-active: 1
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      poolPreparedStatements: true
      share-prepared-statements: true
      maxPoolPreparedStatementPerConnectionSize: 50
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: select 1
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 5000
        wall:
          config:
            multi-statement-allow: true
          db-type: mysql
          enabled: true
      web-stat-filter:
        enabled: false

###mybatis-plus
mybatis-plus:
  ###检测本地配置
  check-config-location: false
  ###mapper文件
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  configuration:
    ###查询map为空是保留字段
    call-setters-on-nulls: true
    ###设置当JDBC类型为空时,某些驱动程序 要指定值
    jdbc-type-for-null: null
    ###下划线转驼峰
    map-underscore-to-camel-case: true
  global-config:
    ###打印banner
    banner: false
    ###刷新mapper
    refresh: true
    db-config:
      ###更新策略
      field-strategy: not_null
      ###主键类型
      id-type: auto

###日志设置配置
logging:
  file: krt.log
  file.max-history: 7
  level:
    com:
      krt: DEBUG
    javamelody: ERROR
    root: INFO
    springfox:
      documentation:
        swagger: ERROR

###swagger 配置
swagger:
  base-package: com.krt.sys.controller
